from django.contrib import admin
from django.urls import path,include
from silverapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.userlogin,name='login'),
    path('forgotpass/',views.forgot,name='forgot'),
    path('subusers/',views.subusers,name='subusers'),
    path('add_subusers/',views.subuser_add,name='block'),
    path('changepass/',views.change_pass,name='changepass'),
    path('edit_subusers/<int:id>/',views.edit_subusers,name='edit_subusers'),
    path('view_subusers/<int:id>/',views.view_subusers,name='view_subusers'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('deletedata/<int:id>',views.deletedata),
    path('logout/', views.logout_view, name='logout'),
    path('submasters/',views.submasters,name='submasters'),
    path('add_submasters/',views.add_submasters,name='add_submasters'),
    path('edit_submasters/<int:id>/',views.edit_submasters,name='edit_submasters'),
    path('view_submasters/<int:id>/',views.view_submasters,name='view_submasters'),
    path('login_log/',views.login_log,name='login_log'),
    path('settings_silver/',views.settings_silver,name='setings_silver'),
    path('delete_submaster/<int:id>/', views.delete_submaster, name='delete_submaster'),
    path('categories/',views.category_list,name='categories'),
    path('categories/delete/', views.delete_categories, name='delete_categories'),
    path('add_category/',views.add_category,name="add_category"),
    path('edit_category/<int:id>/',views.edit_category,name="edit_category"),
    path('delete_categories/<int:id>/',views.delete_categories,name='delete_categories'),
    path('motor_rating/',views.motor_rating,name='motor_rating'),
    path('add_motor/',views.add_motor,name='add_motor'),
    path('edit_motor/<int:id>/',views.edit_motor,name="edit_motor"),
    path('delete_motor/<int:id>/', views.delete_single_motor, name='delete_single_motor'),
    path('phase/',views.phase,name='phase'),
    path('add_phase/',views.add_phase,name="add_phase"),
    path('edit_phase/<int:id>/',views.edit_phase,name="edit_phase"),
    path('delete_phase/<int:id>/', views.delete_phase, name='delete_phase'),
    path('hertz/',views.hertz,name="hertz"),
    path('add_hertz/',views.add_hertz,name='add_hertz'),
    path('edit_hertz/<int:id>/',views.edit_hertz,name='edit_hertz'),
    path('delete_hertz/<int:id>/', views.delete_single_hertz, name='delete_hertz'),
    path('rpm/',views.rpm,name='rpm'),
    path('add_rpm/',views.add_rpm,name='add_rpm'),
    path('edit_rpm/<int:id>/',views.edit_rpm,name='edit_rpm'),
    path('delete_single_rpm/<int:id>/', views.delete_single_rpm, name='delete_single_rpm'),
    path('pipesize/',views.pipesize,name="pipesize"),
    path('add_pipesize/',views.add_pipesize,name='add_pipesize'),
    path('edit_pipesize/<int:id>/',views.edit_pipesize,name='edit_pipesize'),
    path('delete_pipesize/<int:id>/', views.delete_pipesize, name='delete_pipesize'),
    path('size/',views.size,name="size"),
    path('add_size/',views.add_size,name='add_size'),
    path('edit_size/<int:id>/',views.edit_size,name='edit_size'),
    path('delete_size/<int:id>/', views.delete_size, name='delete_size'),
    path('discharge_unit/',views.discharge_unit,name="discharge_unit"),
    path('edit_discharge_unit/<int:id>/',views.edit_discharge_unit,name="edit_discharge_unit"),
    path('discharge/',views.discharge,name="discharge"),
    path('add_discharge/',views.add_discharge,name='add_discharge'),
    path('edit_discharge/<int:id>/',views.edit_discharge,name='edit_discharge'),
    path('delete_discharge/<int:id>/', views.delete_discharge, name='delete_discharge'),
    path('motor_body/',views.motor_body,name='motor_body'),
    path('add_motor_body/',views.add_motor_body,name='add_motor_body'),
    path('edit_motor_body/<int:id>/',views.edit_motor_body,name='edit_motor_body'),
    path('delete_motor_body/<int:id>/',views.delete_motor_body,name='delete_motor_body'),
    path('certifications/',views.certifications,name='certifications'),
    path('add_certifications/',views.add_certifications,name='add_certifications'),
    path('edit_certifications/<int:id>/',views.edit_certifications,name='edit_certifications'),
    path('delete_certifications/<int:id>/',views.delete_certifications,name='delete_certifications'),
    path('motor_rotor_material/',views.motor_rotor_material,name='motor_rotor_material'),
    path('add_motor_rotor/',views.add_motor_rotor,name='add_motor_rotor'),
    path('edit_motor_rotor/<int:id>/',views.edit_motor_rotor,name='edit_motor_rotor'),
    path('delete_motor_rotor/<int:id>/',views.delete_motor_rotor,name='delete_motor_rotor'),
    path('impeller/',views.impeller,name='impeller'),
    path('add_impeller/',views.add_impeller,name='add_impeller'),
    path('edit_impeller/<int:id>/',views.edit_impeller,name='edit_impeller'),
    path('delete_impeller/<int:id>/',views.delete_impeller,name='delete_impeller'),
    path('motor_type/',views.motor_type,name='motor_type'),
    path('add_motor_type/',views.add_motor_type,name='add_motor_type'),
    path('edit_motor_type/<int:id>/',views.edit_motor_type,name='edit_motor_type'),
    path('delete_motor_type/<int:id>/',views.delete_motor_type,name='delete_motor_type'),
    path('star_rating/',views.star_rating,name='star_rating'),
    path('add_star_rating/',views.add_star_rating,name='add_star_rating'),
    path('edit_star_rating/<int:id>/',views.edit_star_rating,name='edit_star_rating'),
    path('delete_star_rating/<int:id>/',views.delete_star_rating,name='delete_star_rating'),
    path('products/',views.products,name='products'),
    path('add_product/',views.add_product,name='add_product'),
    path('edit_product/<int:id>/',views.edit_product,name='edit_product'),
    path('delete_product/<int:id>/',views.delete_product,name='delete_product'),
    path('edit_fill_data/<int:id>/',views.edit_fill_data,name='edit_fill_data'),
    path('view_product/<int:id>/',views.view_product,name='view_product'),

    
    
    
    

]
