# Generated by Django 4.2 on 2025-06-21 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('foldername', models.CharField(blank=True, default='', max_length=100)),
                ('licence_domain', models.CharField(blank=True, default='', max_length=255)),
                ('embed_domain', models.CharField(blank=True, default='', max_length=255)),
                ('access_code', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('zipcode', models.CharField(blank=True, default='', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('fax', models.CharField(blank=True, default='', max_length=50)),
                ('database_host', models.CharField(blank=True, default='', max_length=255)),
                ('db_username', models.CharField(blank=True, default='', max_length=100)),
                ('db_name', models.CharField(blank=True, default='', max_length=100)),
                ('db_password', models.CharField(blank=True, default='', max_length=100)),
                ('licence_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tools_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('login_screenlogo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('allowed', models.IntegerField(blank=True, default=0, null=True)),
                ('unlimited', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmasterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('allowed', models.IntegerField(blank=True, default=0, null=True)),
                ('unlimited', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='add_subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login_id', models.CharField(max_length=15, unique=True)),
                ('foldername', models.CharField(max_length=12)),
                ('licence_domain', models.CharField(max_length=15)),
                ('embed_domain', models.CharField(max_length=15)),
                ('licence_logo', models.ImageField(upload_to='images/')),
                ('tools_logo', models.ImageField(upload_to='images/')),
                ('login_screenlogo', models.ImageField(upload_to='images/')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('access_code', models.BigIntegerField()),
                ('address', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('fax', models.CharField(max_length=15)),
                ('database_host', models.CharField(default='localhost:127.0.0.1', max_length=20)),
                ('db_username', models.CharField(default='root', max_length=20)),
                ('db_name', models.CharField(default='mysql', max_length=20)),
                ('db_password', models.CharField(default='', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('allowed_number', models.IntegerField(default=0)),
                ('unlimited', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
