# Generated by Django 4.2 on 2025-06-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0003_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_star_message', models.CharField(default='No Star', max_length=255)),
                ('head_unit', models.CharField(default='Meters', max_length=50)),
                ('discharge_unit', models.CharField(default='LPH - Liter Per Hour', max_length=50)),
                ('rating_unit', models.CharField(default='HP', max_length=50)),
                ('per_page', models.IntegerField(default=10)),
                ('help_head', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
