# Generated by Django 4.2 on 2025-06-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='account_name',
            new_name='account',
        ),
        migrations.AddField(
            model_name='category',
            name='discharge_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category_images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryMasterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_area', models.CharField(max_length=100)),
                ('is_applicable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverapp.category')),
            ],
        ),
    ]
