# Generated by Django 4.2 on 2025-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0007_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account', models.CharField(choices=[('Pump Demo', 'Pump Demo'), ('Pump A', 'Pump A'), ('Pump B', 'Pump B')], max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
