# Generated by Django 4.2 on 2025-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0008_motorrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('account', models.CharField(default='Pump Demo', max_length=100)),
            ],
        ),
    ]
