# Generated by Django 4.2 on 2025-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0010_hertz'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpm_name', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
