# Generated by Django 4.2 on 2025-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0011_rpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_size', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='pipesizes', to='silverapp.category')),
            ],
        ),
    ]
