# Generated by Django 4.2 on 2025-07-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0012_pipesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Star Rating Name')),
                ('account', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('pipe_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.pipesize')),
            ],
        ),
    ]
