# Generated by Django 4.2 on 2025-07-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0013_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='star_rating',
        ),
    ]
