# Generated by Django 4.2 on 2025-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0014_rename_name_size_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='pipe_size',
        ),
        migrations.AddField(
            model_name='size',
            name='pipe_sizes',
            field=models.ManyToManyField(blank=True, to='silverapp.pipesize'),
        ),
    ]
