# Generated by Django 4.2 on 2025-07-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0015_remove_size_pipe_size_size_pipe_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('M3/HR', 'M3/HR'), ('LPS', 'LPS'), ('LPH', 'LPH'), ('LPM', 'LPM')], max_length=20, unique=True)),
                ('denotes', models.CharField(max_length=100)),
                ('decimal_places', models.PositiveIntegerField(default=0)),
                ('account', models.CharField(default='Pump Demo', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
