# Generated by Django 4.2 on 2025-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0017_discharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
