# Generated by Django 4.2 on 2025-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0018_alter_discharge_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.CharField(default='Pump Demo', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
