# Generated by Django 4.2 on 2025-07-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0019_motormaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motormaterial',
            name='categories',
            field=models.ManyToManyField(blank=True, to='silverapp.category'),
        ),
    ]
