# Generated by Django 4.2 on 2025-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0021_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorRotorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_rotor_name', models.CharField(max_length=100)),
                ('account', models.CharField(default='Pump Demo', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
