# Generated by Django 4.2 on 2025-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0022_motorrotormaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorrotormaterial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
