# Generated by Django 4.2 on 2025-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0023_alter_motorrotormaterial_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpellerMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impeller_name', models.CharField(max_length=100)),
                ('account', models.CharField(default='Pump Demo', max_length=100)),
                ('categories', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
    ]
