# Generated by Django 4.2 on 2025-07-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0024_impellermaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motormaterial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='impellermaterial',
            name='categories',
        ),
        migrations.AddField(
            model_name='impellermaterial',
            name='categories',
            field=models.ManyToManyField(blank=True, to='silverapp.category'),
        ),
    ]
