# Generated by Django 4.2 on 2025-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0025_remove_motormaterial_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impellermaterial',
            name='status',
        ),
        migrations.AddField(
            model_name='impellermaterial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impellermaterial',
            name='long_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
