# Generated by Django 4.2 on 2025-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0026_remove_impellermaterial_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_type_name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, to='silverapp.category')),
            ],
        ),
    ]
