# Generated by Django 4.2 on 2025-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0027_motortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='motortype',
            name='long_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
