# Generated by Django 4.2 on 2025-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0028_motortype_long_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating_name', models.CharField(max_length=100)),
                ('account', models.CharField(default='Pump Demo', max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
