# Generated by Django 4.2 on 2025-07-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0029_starrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('account', models.CharField(default='Pump Demo', max_length=100)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='product/thumbs/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='product/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='silverapp.category')),
                ('discharge_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.dischargeunit')),
            ],
        ),
    ]
