# Generated by Django 4.2 on 2025-07-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0030_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
