# Generated by Django 4.2 on 2025-07-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0031_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discharge_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silverapp.dischargeunit'),
        ),
    ]
