# Generated by Django 4.2 on 2025-07-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0032_remove_product_discharge_unit_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discharges',
            field=models.ManyToManyField(to='silverapp.discharge'),
        ),
        migrations.AddField(
            model_name='product',
            name='motor_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.motorrating'),
        ),
        migrations.AddField(
            model_name='product',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.phase'),
        ),
        migrations.AddField(
            model_name='product',
            name='pipe_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.pipesize'),
        ),
        migrations.AddField(
            model_name='product',
            name='rpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.rpm'),
        ),
    ]
