# Generated by Django 4.2 on 2025-07-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0033_product_discharges_product_motor_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discharges',
            new_name='discharge',
        ),
    ]
