# Generated by Django 4.2 on 2025-07-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0034_rename_discharges_product_discharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hertz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.hertz'),
        ),
    ]
