# Generated by Django 4.2 on 2025-07-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0035_product_hertz'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorPumpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge', models.IntegerField()),
                ('head', models.FloatField()),
                ('recommend', models.BooleanField(default=False)),
                ('motor_rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.motorrating')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.phase')),
                ('pipe_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silverapp.pipesize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverapp.product')),
            ],
        ),
    ]
