# Generated by Django 4.2 on 2025-07-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverapp', '0036_motorpumpdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='silverapp.dischargeunit'),
            preserve_default=False,
        ),
    ]
